TEST_PLAYER_ENTITY_NUMBER = 2222
TEST_PLAYER_DISCORD_ID = 100
TEST_PLAYER_DISCORD_NAME = 'player'

TEST_ITEM_ENTITY_NUMBER = 200
TEST_ITEM_ENTITY_REFERENCE = '/5k'
TEST_ITEM_ENTITY_NUMBER_2 = 201
TEST_ITEM_ENTITY_REFERENCE_2 = '/5l'

MESSAGE_TEST_PLAYER_INCAPACITATED = '<@100> You are incapacitated.'
